spring.application.name=video-streaming-api

# Server Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/video_streaming
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Logging
logging.level.com.videostreaming.api=INFO
logging.level.org.hibernate.SQL=DEBUG

# Credit Card HMAC Secret (use a strong random value in production)
app.credit-card.hmac-secret=vStr3amingS3cr3tK3y!2026#HmacSHA256
